# Generated by Django 5.1.1 on 2024-10-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFTListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField(unique=True)),
                ('seller_address', models.CharField(max_length=42)),
                ('sale_price', models.DecimalField(decimal_places=18, max_digits=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
